# Generated by Django 5.2 on 2025-09-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
