# Generated by Django 5.2 on 2025-09-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_shop_alter_product_image_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("position", models.TextField()),
                ("description", models.TextField()),
                ("content", models.TextField()),
            ],
        ),
    ]
