# Generated by Django 5.2 on 2025-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0004_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="name",
            field=models.CharField(),
        ),
    ]
